services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: catalogo_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: catalogo
      RABBITMQ_DEFAULT_PASS: catalogo
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16
    container_name: catalogo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalogo_db
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: catalogo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: